Exam
mrniktarasov/2019-2-Atom-Frontend-N-Tarasov pull request #11
Opened 2019-12-17 18:10 UTC by mrniktarasov

# Экзамен

Прошу @martinkomitsky, @chexex или @priver проверить его.

Что было сделано:
* Сделан роутинг
* Добавлен плохой дизайн
*

2019-12-19 05:12 UTC, martinkomitsky requested changes
Ждем выполнения задания до конца

2019-12-19 05:41 UTC, mrniktarasov commented
Все будет

2019-12-19 18:09 UTC, mrniktarasov commented
Доделал экзамен

2019-12-19 18:13 UTC, mrniktarasov commented
https://mrniktarasov.github.io/2019-2-Atom-Frontend-N-Tarasov/

2019-12-20 06:35 UTC, martinkomitsky requested changes
Замечания:
![image](https://user-images.githubusercontent.com/14847018/71234989-d5fd9680-230b-11ea-92af-c588cd74071b.png)
0. Исправить замечания по коду
1. Некоторые данные могут отсутствовать. Нужно сделать проверку на наличие данных перед выводом данных
2. Если запросить пустую строку или неизвестный API город, то верстка ломается
![image](https://user-images.githubusercontent.com/14847018/71235035-01808100-230c-11ea-8970-357c3a1945f5.png)

2019-12-20 06:35 UTC, martinkomitsky commented on exam/stylelint.config.js
> +	*/
мусор

2019-12-20 06:35 UTC, martinkomitsky commented on exam/src/reducers/cities.js
> +			let cities = [...state.cities];
```suggestion
			const cities = [...state.cities];
```

2019-12-20 06:38 UTC, martinkomitsky commented on exam/src/components/CityProfile.js
> +	if (currentDate.getMonth() === 0 || currentDate.getMonth() === 9) {
`currentDate.getMonth()` вызывается ~500 раз)) Нужно выполнить это 1 раз, сохранить в константу и далее по коду использовать ее

2019-12-20 12:21 UTC, mrniktarasov commented
Доделал правки

2019-12-20 13:56 UTC, martinkomitsky approved these changes

2019-12-20 13:56 UTC, merged