Homework 2
mrniktarasov/2019-2-Atom-Frontend-N-Tarasov pull request #2
Opened 2019-10-13 18:14 UTC by mrniktarasov

# Домашнее задание №

Прошу @martinkomitsky, @chexex или @priver проверить его.
Вроде все работает.
Что было сделано:
* 
*
*

2019-10-13 18:16 UTC, mrniktarasov commented
Тесты не работают, извините.

2019-10-14 07:59 UTC, mrniktarasov commented
У меня локально тесты работают.

2019-10-14 10:16 UTC, priver requested changes
Нужно выкатить чат на github pages

2019-10-14 10:16 UTC, priver commented on web-components/src/components/MessageForm.js
> +		for (let element = 0; element < localStorage.length - 1; element += 1) {
Нужно создать массив messages и записать его в localStorage целиком в один ключ. Иначе мы весь сторадж под один чат заняли.

Как поведет себя программа, если я запишу в localStorage ключ myKey? length увеличится на 1, а элемента с ключем [length - 1] в сторадже не будет

В твоем случае `element < localStorage.length - 1` вместо `element < localStorage.length` - это костыль

2019-10-14 10:16 UTC, priver commented on nano.save
> +U
это какой то ненужный файл

2019-10-14 10:16 UTC, priver commented on web-components/src/components/MessageForm.js
> +/* eslint-disable no-tabs */
это почему?

2019-10-14 12:35 UTC, mrniktarasov commented on web-components/src/components/MessageForm.js
> +/* eslint-disable no-tabs */
eslint ругается на то, что присваивание не деструктуририующее и на табы

2019-10-14 12:36 UTC, mrniktarasov commented on nano.save
> +U
Хорошо, я его удалю

2019-10-14 15:40 UTC, mrniktarasov commented on web-components/src/components/MessageForm.js
> +		for (let element = 0; element < localStorage.length - 1; element += 1) {
>Нужно создать массив messages и записать его в localStorage целиком в один ключ. Иначе мы весь сторадж под один чат заняли.
Вы имеете в виду создать масстив в конструкторе и к нему обращаться?
Или создать массив, записать его в localStorage, после чего извлекать его оттуда при каждом новом сообщении, записывать туда новое значение и записывать обратно?

2019-10-14 17:18 UTC, mrniktarasov commented on web-components/src/components/MessageForm.js
> +		for (let element = 0; element < localStorage.length - 1; element += 1) {
>Нужно создать массив messages и записать его в localStorage целиком в один ключ. Иначе мы весь сторадж под один чат заняли.
Вы имеете в виду создать масстив в конструкторе и к нему обращаться?
Или создать массив, записать его в localStorage, после чего извлекать его оттуда при каждом новом сообщении, записывать туда новое значение и записывать обратно?

> Нужно создать массив messages и записать его в localStorage целиком в один ключ. Иначе мы весь сторадж под один чат заняли.
> 
> Как поведет себя программа, если я запишу в localStorage ключ myKey? length увеличится на 1, а элемента с ключем [length - 1] в сторадже не будет
> 
> В твоем случае `element < localStorage.length - 1` вместо `element < localStorage.length` - это костыль



> Нужно создать массив messages и записать его в localStorage целиком в один ключ. Иначе мы весь сторадж под один чат заняли.
> 
> Как поведет себя программа, если я запишу в localStorage ключ myKey? length увеличится на 1, а элемента с ключем [length - 1] в сторадже не будет
> 
> В твоем случае `element < localStorage.length - 1` вместо `element < localStorage.length` - это костыль


> Нужно создать массив messages и записать его в localStorage целиком в один ключ. Иначе мы весь сторадж под один чат заняли.
> 
> Как поведет себя программа, если я запишу в localStorage ключ myKey? length увеличится на 1, а элемента с ключем [length - 1] в сторадже не будет
> 
> В твоем случае `element < localStorage.length - 1` вместо `element < localStorage.length` - это костыль

Вы имеете в виду создать масстив в конструкторе и к нему обращаться?
Или создать массив, записать его в localStorage, после чего извлекать его оттуда при каждом новом сообщении, записывать туда новое значение и записывать обратно?

2019-10-14 17:48 UTC, mrniktarasov commented on web-components/src/components/MessageForm.js
> +		for (let element = 0; element < localStorage.length - 1; element += 1) {
>Как поведет себя программа, если я запишу в localStorage ключ myKey? length увеличится на 1, а элемента с ключем [length - 1] в сторадже не будет
Сохраниться со значением больше на 1. Можно поставить проверку, что элемент "ID-${element}" не undefined

2019-10-15 14:11 UTC, priver commented on web-components/src/components/MessageForm.js
> +		for (let element = 0; element < localStorage.length - 1; element += 1) {
> Можно поставить проверку, что элемент "ID-${element}" не undefined

и делать лишние итерации в цикле?

> Или создать массив, записать его в localStorage, после чего извлекать его оттуда при каждом новом сообщении, записывать туда новое значение и записывать обратно?

именно так

2019-10-15 14:12 UTC, priver commented on web-components/src/components/MessageForm.js
> +/* eslint-disable no-tabs */
ну значит наверное должны быть пробелы?

2019-10-15 21:00 UTC, mrniktarasov commented on web-components/src/components/MessageForm.js
> +		for (let element = 0; element < localStorage.length - 1; element += 1) {
Сделал

2019-10-15 21:06 UTC, mrniktarasov commented
Добавил чат на github pages

2019-10-16 15:09 UTC, mrniktarasov commented
Исправил трэвис

2019-10-17 10:41 UTC, priver requested changes
Нужно сделать скролл до последнего сообщения (до низа окна) при сабмите

2019-10-17 10:41 UTC, priver commented on web-components/src/components/MessageForm.js
> +    if (localStorage.length > 0) {
вот эта проверка ничего не делает (все что нужно порверяется в if ниже)

2019-10-17 13:24 UTC, mrniktarasov commented
Сделал

2019-10-18 10:01 UTC, priver approved these changes
Теперь все хорошо, 12 баллов

2019-10-18 10:01 UTC, merged