Homework 3
mrniktarasov/2019-2-Atom-Frontend-N-Tarasov pull request #4
Opened 2019-10-21 20:18 UTC by mrniktarasov

# Домашнее задание № 3

Прошу @martinkomitsky, @chexex или @priver проверить его.

Что было сделано:
* Добавил панель с чатами
* Добавил кнопку создать чат
* Добавил переход в окно чата и обратно

2019-10-21 20:26 UTC, mrniktarasov commented
Я задеплоил ветку, я не знаю, почему здесь этого не видно

2019-10-21 20:34 UTC, mrniktarasov commented
https://mrniktarasov.github.io/2019-2-Atom-Frontend-N-Tarasov/

2019-10-21 20:35 UTC, mrniktarasov commented
Картинки не работают, извините

2019-10-22 04:09 UTC, martinkomitsky requested changes
Нужно исправить замечания по коду + эти замечания ниже:
1. Починить картинки. Так как у тебя после деплоя сервер смотрит в папочку `build`, он там картинок не находит, соответственно, у тебя 404. Чтобы картинки там появились, я предлагаю добавить такую [надстройку](https://github.com/webpack-contrib/copy-webpack-plugin) в этап сборки вебпака. Нужно указать источник своих картинок (папку) и место, куда оно будет копироваться (`build/<как сам назовешь>)`. Абсолютные пути должны будут совпадать
2. Когда я открываю чат, пишу туда что-то, мои сообщения не сохраняются. Нужно починить, чтобы сообщения хранились для каждого чата
3. На экране чата у тебя сообщения подлезают под шапку, чего быть точно не должно
![image](https://user-images.githubusercontent.com/14847018/67258925-abbe6280-f49b-11e9-95fb-0fc44b56086b.png)

2019-10-22 04:09 UTC, martinkomitsky commented on web-components/build/index.html
>    <body>
Папка `build` должна быть в gitignore, а в репозиторий ее комитить нельзя. Удалить срочно!

2019-10-22 04:11 UTC, martinkomitsky commented on web-components/src/components/chat/chatHeader.js
> +/* eslint-disable no-underscore-dangle */
Не нужно повторять от файла к файлу все эти строчки. Линтер создан для того, чтобы следовать его правилам, а не выключать, иначе какой смысл? Убираешь правила, делаешь автофикс ошибок:
```
eslint --fix .
```
После этого есть 2 сценария. Либо остальное правишь ручками, либо, если правило не нравится, переопределяешь его в секции `rules` в `.eslintrc`

2019-10-22 04:12 UTC, martinkomitsky commented on web-components/src/components/groups/addGroup.js
> +/* eslint-disable consistent-return */
Убрать все это и сделать по-нормальному, как писал выше

2019-10-22 18:10 UTC, mrniktarasov commented
Доделал правки

2019-10-22 18:11 UTC, mrniktarasov commented
В версии на гитхабе пользоватееля перекидывает на стартовый экран после написания сообщения. В localhost сайте этого нет.

2019-10-22 19:43 UTC, mrniktarasov commented
Доделал

2019-10-23 09:44 UTC, mrniktarasov commented
Сейчас вроде нормально работает.

2019-10-23 20:59 UTC, mrniktarasov commented
> В версии на гитхабе пользоватееля перекидывает на стартовый экран после написания сообщения. В localhost сайте этого нет.

Это верно для Mozilla, в хроме все работает.

2019-10-24 07:45 UTC, martinkomitsky approved these changes

2019-10-24 07:45 UTC, merged

2019-10-24 07:45 UTC, martinkomitsky commented
10 + 2