Devel
mrniktarasov/2019-2-Atom-Frontend-N-Tarasov pull request #6
Opened 2019-11-11 08:38 UTC by mrniktarasov

# Домашнее задание № 5

Прошу @martinkomitsky, @chexex или @priver проверить его.

Что было сделано:
* Приложение переписано на реакт (в папке react-web-components)
* Я не называю ветку номером ДЗ и использую ветку девел, чтобы не вписывать в .travis.yml название ветки, однако если это необходимо, то буду.
*

2019-11-11 15:49 UTC, mrniktarasov commented
https://mrniktarasov.github.io/2019-2-Atom-Frontend-N-Tarasov/

2019-11-12 04:51 UTC, martinkomitsky commented on package.json
> +		"ci": "npm run test && npm run build && npm run test:sec"
У тебя не работает линтер. Замени эти скрипты на следующие:

```
		"predeploy": "npm run build",
		"deploy": "gh-pages -d build",
		"start": "react-scripts start",
		"build": "react-scripts build",
		"eject": "react-scripts eject",
		"format": "prettier --write '**/*.{js,jsx,json,md}'",
		"format:changed": "pretty-quick",
		"format:staged": "pretty-quick --staged",
		"lint": "npm run lint:js && npm run lint:dup && npm run lint:css",
		"lint:check": "eslint --print-config .eslintrc.json | eslint-config-prettier-check",
		"lint:js:fix": "npm run lint:js -- --fix",
		"lint:js": "eslint src/**/*.js -c .eslintrc.json",
		"lint:css": "stylelint 'src/**/*.{scss,css}' && stylelint --rd 'src/**/*.{scss,css}'",
		"lint:dup": "jscpd -g --threshold=1 tests docker",
		"clean": "rm -rf build",
		"test": "npm run test:engine && npm run lint",
		"test:engine": "check-engine",
		"test:sec": "npm audit || true",
		"test:unit": "react-scripts test",
		"ci": "npm run test && npm run build && npm run test:sec"
```

2019-11-12 04:51 UTC, martinkomitsky commented on package.json
> +			"pre-commit": "pretty-quick --staged"
```suggestion
			"pre-commit": "npm run lint && npm run format:staged"
```

2019-11-12 04:53 UTC, martinkomitsky requested changes
Заменить скрипты и запускать линтер перед коммитом. Нужно  добиться зеленой сборки в тревисе

2019-11-12 13:09 UTC, mrniktarasov commented
После того, как я исправляю globalStyles.css, после коммита этотй файл исправляется обратно.

2019-11-12 17:33 UTC, martinkomitsky requested changes
1. Открываем [PR](https://github.com/mrniktarasov/2019-2-Atom-Frontend-N-Tarasov/pull/6/files).
2. Самостоятельно проверяем на предмет ненужных файлов (мусор, сборка и т.д.)
3. Удаляем этот мусор, добавляем в гит игнор.
4. Добиваемся того, чтобы сборка проходила. Для этого надо починить стили по правилам линтера.
![image](https://user-images.githubusercontent.com/14847018/68695059-69b0aa00-058b-11ea-9bc9-c8594e6c628f.png)
5. Думаем о том, почему реакт был перенесен в отдельную папку. Не уверен, что это было лучшим решением.

2019-11-12 19:11 UTC, mrniktarasov commented
>     5. Думаем о том, почему реакт был перенесен в отдельную папку. Не уверен, что это было лучшим решением.
Нужно переместить в корневую папку?

2019-11-13 20:47 UTC, mrniktarasov commented
Тесты линтера проходят

2019-11-14 04:38 UTC, chexex commented
Токен добавлен в трэвисе?

2019-11-14 07:55 UTC, mrniktarasov commented
Сборка проходит

2019-11-14 08:31 UTC, martinkomitsky commented on webpack.config.js
> +};
что это такое? Зачем добавил?

2019-11-14 08:35 UTC, martinkomitsky requested changes
1. Убрать вебпак конфиг из корня.
2. Починить доскролл вниз после появления сообщения

2019-11-14 17:46 UTC, mrniktarasov commented
Починил скролл

2019-11-14 17:46 UTC, mrniktarasov commented on webpack.config.js
> +};
Я не знаю

2019-11-14 17:47 UTC, mrniktarasov commented on webpack.config.js
> +};
От веб компонентоа осталось

2019-11-15 15:58 UTC, mrniktarasov commented
Убрал вебпак

2019-11-16 15:28 UTC, martinkomitsky approved these changes
12

2019-11-16 15:28 UTC, merged