Homework 7
mrniktarasov/2019-2-Atom-Frontend-N-Tarasov pull request #8
Opened 2019-11-24 13:18 UTC by mrniktarasov

# Домашнее задание № 7

Прошу @martinkomitsky, @chexex или @priver проверить его.

Что было сделано:
*Добавлена запись аудио и отправка картинок через драгдроп, отправка геолокации
*
*

2019-11-24 13:22 UTC, mrniktarasov commented
https://mrniktarasov.github.io/2019-2-Atom-Frontend-N-Tarasov/

2019-12-02 07:48 UTC, mrniktarasov commented
.

2019-12-03 11:33 UTC, priver requested changes
![image](https://user-images.githubusercontent.com/1700074/70047795-d262d380-15d9-11ea-8a29-52c523686c6f.png)

эта кнопка не нажимается

2019-12-03 11:33 UTC, priver commented on src/components/Chat/FormInput/PaperClip/PaperClip.js
> +	window.addEventListener('click', handleOtherClick);
обработчик будет добавляться при каждом вызове. нужно вызывать его в `useEffect`:

```js
React.useEffect(() => {
    window.addEventListener('click', handleOtherClick);

    return () => {
       window.removeEventListener('click', handleOtherClick);
    };
}, []);
```

Саму функцию тогда придется либо вынести из компонента, либо использовать useCallback (иначе это будут разные функции).

Также, функция будет использовать всегда один и тот же  `styles `, и если значение свойства изменится - функция все равно будет видеть старое значение свойства из замыкания. Как вариант - создать `ref` и изменять его значение при изменении свойств. Или удалять и навешивать новый обработчик при изменении свойства (добавить его во второй аргумент `useEffect`)

2019-12-03 11:33 UTC, priver commented on src/components/Chat/FormInput/Microphone/Microphone.js
> +		navigator.mediaDevices.getUserMedia(constrains).then((stream) => {
здесь нужен `catch`, пользователь может запретить доступ к микрофону

2019-12-03 12:02 UTC, mrniktarasov commented on src/components/Chat/FormInput/PaperClip/PaperClip.js
> +	window.addEventListener('click', handleOtherClick);
> Саму функцию тогда придется либо вынести из компонента, либо использовать useCallback (иначе это будут разные функции).
Вы имеете в ввиду функцию handleClick?

2019-12-03 13:19 UTC, mrniktarasov commented on src/components/Chat/FormInput/PaperClip/PaperClip.js
> +	window.addEventListener('click', handleOtherClick);
Понял

2019-12-03 15:11 UTC, mrniktarasov commented
Доделал, что мог, но к пункту 

> Также, функция будет использовать всегда один и тот же styles , и если значение свойства изменится - функция все равно будет видеть старое значение свойства из замыкания.

мне нужны пояснения т.к. я ничего не понял.

2019-12-03 18:31 UTC, mrniktarasov commented
Доделал

2019-12-04 16:56 UTC, priver commented
давай я тебе на семинаре тогда подробнее расскажу, напомнишь?

2019-12-04 16:56 UTC, priver approved these changes

2019-12-04 16:56 UTC, merged